- name: reza-alipour/SARC_Sarcasm
  freqs: 2
  class_nums: 2
  loss: BCE
  label_to_id:
    0: 0
    1: 1
- name: reza-alipour/Yelp_Sentiment
  freqs: 1
  loss: BCE
  class_nums: 2
  label_to_id:
    0: 0
    1: 1