- name: reza-alipour/SemEvalTask3_SubTask1
  freqs: 1
  class_nums: 3
  loss: CE
  label_to_id:
    satire: 0
    opinion: 1
    reporting: 2
  loss_weights:
    - 86.0
    - 3.0
    - 21.0
- name: reza-alipour/SemEvalTask3_SubTask2
  freqs: 1
  loss: BCE
  class_nums: 14
  label_to_id:
    Economic: 0
    Capacity_and_resources: 1
    Morality: 2
    Fairness_and_equality: 3
    Legality_Constitutionality_and_jurisprudence: 4
    Policy_prescription_and_evaluation: 5
    Crime_and_punishment: 6
    Security_and_defense: 7
    Health_and_safety: 8
    Quality_of_life: 9
    Cultural_identity: 10
    Public_opinion: 11
    Political: 12
    External_regulation_and_reputation: 13
  loss_weights:
    - 8.0
    - 12.0
    - 7.0
    - 12.0
    - 9.0
    - 11.0
    - 8.0
    - 6.0
    - 11.0
    - 12.0
    - 20.0
    - 21.0
    - 5.0
    - 7.0
- name: reza-alipour/SemEvalTask3_SubTask3
  freqs: 2
  loss: BCE
  class_nums: 23
  label_to_id:
    Appeal_to_Authority: 0
    Appeal_to_Popularity: 1
    Appeal_to_Values: 2
    Appeal_to_Fear-Prejudice: 3
    Flag_Waving: 4
    Causal_Oversimplification: 5
    False_Dilemma-No_Choice: 6
    Consequential_Oversimplification: 7
    Straw_Man: 8
    Red_Herring: 9
    Whataboutism: 10
    Slogans: 11
    Appeal_to_Time: 12
    Conversation_Killer: 13
    Loaded_Language: 14
    Repetition: 15
    Exaggeration-Minimisation: 16
    Obfuscation-Vagueness-Confusion: 17
    Name_Calling-Labeling: 18
    Doubt: 19
    Guilt_by_Association: 20
    Appeal_to_Hypocrisy: 21
    Questioning_the_Reputation: 22
  loss_weights:
    - 9.0
    - 22.0
    - 11.0
    - 4.0
    - 11.0
    - 10.0
    - 16.0
    - 18.0
    - 20.0
    - 33.0
    - 44.0
    - 15.0
    - 54.0
    - 11.0
    - 1.0
    - 11.0
    - 5.0
    - 20.0
    - 2.0
    - 1.0
    - 10.0
    - 7.0
    - 3.0